[package]
name = "project"
version = "0.3.5"
edition = "2021"
authors = ["Dimitry.D"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scanf = { version = "1.2.1" }




